---
resources:

- name: legacy-concourse-repo
  type: git
  source:
    uri: https://github.com/ebornier-pivotal/legacy-concourse.git

- name: cf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:


- name: legacy-go
  serial: true
  public: true # cf does not shows auth. logs so itis ok
  plan:
  - get: legacy-concourse-repo
    trigger: true
  - task: build-go
    file: legacy-concourse-repo/ci/build-go.yml
  - put: cf
    params:
      manifest: legacy-concourse-repo/go/manifest.yml
      path: build-go/


- name: legacy-c
  serial: true
  public: true # cf does not shows auth. logs so itis ok
  plan:
  - get: legacy-concourse-repo
    trigger: true
  - task: build-c
    file: legacy-concourse-repo/ci/build-c.yml
  - put: cf
    params:
      manifest: legacy-concourse-repo/GoHttp/manifest.yml
      path: build-c/

